services:
  huntarr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: huntarr
    restart: unless-stopped
    ports:
      - "9705:9705"
    volumes:
      - huntarr-config:/config
    environment:
      - TZ=America/New_York
      - DEBUG=true
    develop:
      watch:
        - path: ./
          action: sync
          target: /app

volumes:
  huntarr-config:
    name: huntarr-config